export let Languages = {
	azcli: {name: "Azure CLI", id: "azcli", fileName: '*.azcli'},
	bat: {name: "Batch (win)", id: "bat", fileName: '*.bat'},
	c: {name: "C", id: "c", fileName: '*.c'},
	clojure: {name: "Clojure", id: "clojure", fileName: '*.clj'},
	coffeescript: {name: "CoffeeScript", id: "coffeescript", fileName: '*.coffee'},
	cpp: {name: "C++", id: "cpp", fileName: '*.cpp'},
	csharp: {name: "C#", id: "csharp", fileName: '*.cs'},
	css: {name: "CSS", id: "css", fileName: '*.css'},
	dockerfile: {name: "Dockerfile", id: "dockerfile", fileName: 'Dockerfile'},
	fsharp: {name: "F#", id: "fsharp", fileName: '*.fs'},
	go: {name: "Golang", id: "go", fileName: '*.go'},
	html: {name: "HTML", id: "html", fileName: '*.html'},
	java: {name: "Java", id: "java", fileName: '*.java'},
	javascript: {name: "Javascript", id: "javascript", fileName: '*.js'},
	json: {name: "JSON", id: "json", fileName: '*.json'},
	kotlin: {name: "Kotlin", id: "kotlin", fileName: '*.kt'},
	lua: {name: "Lua", id: "lua", fileName: '*.lua'},
	markdown: {name: "Markdown", id: "markdown", fileName: '*.md'},
	mysql: {name: "MySQL", id: "mysql", fileName: '*.mysql'},
	'objective-c': {name: "Objective-C", id: "objective-c", fileName: '*.m'},
	perl: {name: "Perl", id: "perl", fileName: '*.pl'},
	php: {name: "PHP", id: "php", fileName: '*.php'},
	pgsql: {name: "PostgreSQL", id: "pgsql", fileName: '*.pgsql'},
	python: {name: "Python", id: "python", fileName: '*.py'},
	r: {name: "R", id: "r", fileName: '*.r'},
	ruby: {name: "Ruby", id: "ruby", fileName: '*.rb'},
	rust: {name: "Rust", id: "rust", fileName: '*.rs'},
	shell: {name: "Bash Shell", id: "shell", fileName: '*.sh'},
	sql: {name: "SQL", id: "sql", fileName: '*.sql'},
	swift: {name: "Swift", id: "swift", fileName: '*.swift'},
	text: {name: "Plain Text", id: "text", fileName: '*.txt'},
	typescript: {name: "TypeScript", id: "typescript", fileName: '*.ts'},
	vb: {name: "Visual Basic", id: "vb", fileName: '*.bas'},
	xml: {name: "XML", id: "xml", fileName: '*.xml'},
};

export default Languages
